export const GET_NEW_RELEASE_REQUESTED = 'GET_NEW_RELEASE_REQUESTED';
export const GET_NEW_RELEASE_SUCCESS = 'GET_NEW_RELEASE_SUCCESS';
export const GET_NEW_RELEASE_FAILED = 'GET_NEW_RELEASE_FAILED';

export const GET_PLAYLISTS_REQUESTED = 'GET_PLAYLISTS_REQUESTED';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAILED = 'GET_PLAYLISTS_FAILED';

export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';